### ISSUE TITLE
pip install waymo-open-dataset-tf-2-1-0==1.2.0 error

### ISSUE THREAD

**Issue by betterqiang** [xixioba/waymo_easy_convert#1]
helllo. I meet one erro when  pip install waymo-open-dataset-tf-2-1-0==1.2.0

--------------------------------------------------------------------------------------
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-1-0==1.2.0 (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset-tf-2-1-0==1.2.0
------------------------------------------------------------------------------------
how to resolve？
thanks。
and I need what python version

**Comment by xixioba** [comment]
We don't need to install, just run in the root directory of the warehouse, **waymo_open_dataset** is a local package
The latest python and tensorflow I am using in macoss conda env
```
waymo_easy_convert git:(main) ✗ python --version
Python 3.10.6
```
waymo_easy_convert git:(main) ✗ pip list
```
tensorboard             2.9.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorflow-estimator    2.9.0
tensorflow-macos        2.9.2
tensorflow-metal        0.5.1
```
I tested it again, it should work

**Comment by betterqiang** [comment]
I use  [pip install  waymo-open-dataset-tf-2-1-0==1.2.0]  in linux   success ,  but in windows  faile

thanks

**Comment by xixioba** [comment]
😶In fact, we don't need to install **waymo-open-dataset-tf,** the purpose of this warehouse is to avoid installing it, I just reuse the code of the original warehouse without modifying the instructions, I updated it today
